### ISSUE TITLE
Too much white space at top of page

### ISSUE THREAD

**Issue by lkilcher** [NREL/latex_editing#12]
When using this tool I've received feedback from NREL editors that there is too much white space at the top of the page. I must admit that I agree (e.g. see page 3 of your [Main.pdf](https://github.com/NREL/latex_editing/blob/master/documents/Main.pdf) file). I fixed my file by adding this to the header:

    \addtolength{\topmargin}{-0.6in}

**Comment by AndyClifton** [comment]
Margins are set at line 102 in `nrel.cls`. I've adjusted the top margin to remove that extra 0.6 inches. Please try the modified `nrel.cls` and see if it works for you?

**Comment by lkilcher** [comment]
Wow, you're fast! That fixed it. Also, FYI, I don't know that `0.6in` is exactly the right amount for NREL style guidelines, it just looked about right to me. :)

Also, THANK YOU for putting this repo together!
