### ISSUE TITLE
Bibliography formatting

### ISSUE THREAD

**Issue by lkilcher** [NREL/latex_editing#13]
NREL editors have requested that my bibliography entries be reformatted. In particular:

1. Put titles of TechReports and PhD Theses in quotes and remove the italics from those titles (e.g. in the bibliography of the Main.pdf file, I believe all of the titles should be in quotes).
2. URL links should use standard fonts (currently they are monospaced fonts).

**Comment by AndyClifton** [comment]
The NREL reference style is based on the _Chicago_ reference style (https://communications_resources.nrel.gov/style_guide/references). This is implemented in the class file around lines 155-165, and could be modified relatively easily to accommodate changes in requirements.

And, according to the current style guide:
* Technical report titles should be italicized.
* Thesis titles should be quoted, not italicized

If this is correct, you may have received out-of-date guidance. I'm checking with NREL communications on this.

**Comment by lkilcher** [comment]
OK. I'll let you figure out whether NREL deviates from the Chicago style when it comes to citing NREL TechReports. Perhaps the issue is that NREL 'TP' reports use TechReport formatting, and NREL 'CP' reports use journal-style formatting? Sheri only told me to use quotes and remove italics from the 'CP' entries.

Still two remaining issues in my output ([bib_page.pdf](https://github.com/NREL/latex_editing/files/83485/bib_page.pdf)) when using the nrel.cls (or nrel.bst?):
1) PhdThesis titles are being formatted with italics (see first entry, 'Egeland...')
2) web and DOI links within the bib use monospace font (see, e.g. MicroStrain, and Thomson 2012)

Thank You!

**Comment by AndyClifton** [comment]
Fixed the quotes and monospace font. Let's close this as an issue, and raise a different one that is to check into how NREL's style differs from Chicago?

**Comment by lkilcher** [comment]
Thanks Andy!
