### ISSUE TITLE
Bibliography: number of authors before using 'et al.'?

### ISSUE THREAD

**Issue by lkilcher** [NREL/latex_editing#16]
The template seems to be using 'et al.' for four or more authors. Is this standard CMS? I've received a comment from editing that NREL only uses "et al." when the list of author names is "obnoxiously long".

**Comment by AndyClifton** [comment]
That is the standard for Chicago A style. NREL's guidance on that is not spectacularly helpful. Shall we change it to 10 or more authors?

**Comment by AndyClifton** [comment]
Changed to 10 by setting `maxcitenames = 10` in line 154 of nrel.cls

**Comment by lkilcher** [comment]
For some reason that doesn't seem to have fixed the problem. I'm still getting 'et al.' for 4 authors.

**Comment by lkilcher** [comment]
It looks like this changed the number of authors listed by the \cite command, but the bibliography still has 'et al.'. I think this is the opposite of what we want. That is: we may want 'et al.' in the citation, but the full list of authors in the bib.

On the other hand, I think it's silly for the bib not to match the cite. Let me check with Sheri about whether she actually wants to deviate from CMS on this.

**Comment by lkilcher** [comment]
OK. I confirmed with Sheri that we should use 'et al.' in the `\cite`, but not in the bibliography unless there are 10 authors. So, this needs to be fixed/reopened.

**Comment by AndyClifton** [comment]
Fixed. On line 155 of `nrel.cls` we now have `maxbibnames = 10, maxcitenames = 3`. This gives a maximum of 10 names in the bib before an `et al.` is used, and 3 in the citations in the text. These can be adjusted in future as required.

**Comment by lkilcher** [comment]
It works!
