### ISSUE TITLE
Bibliography: "." placement for journal articles.

### ISSUE THREAD

**Issue by lkilcher** [NREL/latex_editing#17]
For some reason the period after a journal article title is placed outside the quote marks. This deviates from CMS. For example, I'm getting:
> Kolmogorov, A. N. 1941. “Dissipation of Energy in the Locally Isotropic Turbulence”. Ed. by J. C. R. Hunt, O. M. Phillips, and D. Williams, Dokl. Akad. Nauk SSSR 32 (1): 16–18. http://www.jstor.org/stable/51981.

But it should be:
> Kolmogorov, A. N. 1941. “Dissipation of Energy in the Locally Isotropic Turbulence.” Ed. by J. C. R. Hunt, O. M. Phillips, and D. Williams, Dokl. Akad. Nauk SSSR 32 (1): 16–18. http://www.jstor.org/stable/51981.

**Comment by AndyClifton** [comment]
Looks like this can be fixed using the solution described at http://tex.stackexchange.com/questions/157385/move-periods-inside-quotes-in-bibliography. I'll implement this in the NREL class soon.

**Comment by lkilcher** [comment]
That didn't quite fix it, but it pointed me in the right direction. Here's what I did to fix this: change `english` to `american` in lines 134 and 157 of `nrel.cls`.

**Comment by lkilcher** [comment]
You Brits just lack good `style`. ;)

**Comment by AndyClifton** [comment]
Updated lines 134 and 157 of the `nrel.cls` class file to use `american` instead of `english`. Only mildly upset.
