### ISSUE TITLE
Footnote numbering.

### ISSUE THREAD

**Issue by lkilcher** [NREL/latex_editing#18]
NREL editing wants footnote numbering to increase throughout the document, not reset at `\chapter{}` commands.

Also, Sheri and I discussed that perhaps appendix footnotes could use `*`, `\dagger`, `\ddagger`, etc. I was able to use these symbols by placing:

     \renewcommand*{\thefootnote}{\fnsymbol{footnote}}

after my `\appendix` command.
Assuming you're able to get the footnote numbering to be continuous, we may need to add a `\setcounter{\footnote}{0}` here too.

Can this code be incorporated into the `\appendix` statement?

**Comment by AndyClifton** [comment]
Fixed. Added to the redefinition of the `\appendix` statement. User does not have to do anything.

**Comment by lkilcher** [comment]
This looks great! It just needs a `\setcounter{footnote}{0}` added to the `\appendix` statement. i.e. see my inline-comment to your commit.

**Comment by AndyClifton** [comment]
Added that
