### ISSUE TITLE
Appendix figure numbering.

### ISSUE THREAD

**Issue by lkilcher** [NREL/latex_editing#19]
Figure numbering in the appendix should restart and have the appendix alpha-character number associated with it. For example, figures in Appendix A should be numbered 'A1', 'A2', ..., and Appendix B should be numbered 'B1', 'B2', ....

I was able to fix this manually be inserting the following after each of my appendix `\chapter{}`s:

    \renewcommand{\thefigure}{A\arabic{figure}}
    \setcounter{figure}{0}

Obviously changing the 'A' to a 'B' for the second appendix. It would be nice if this was somehow automatically included with the `\appendix` statement.

**Comment by AndyClifton** [comment]
The `nrel.cls` file uses the `changcntr` package for documents that include chapters. This means that you can use the simpler solution outlined at http://tex.stackexchange.com/a/85779/29222 for tables and figures. 

In practice, to use this in a document, you would do something like this:
```
\appendix
\counterwithin{figure}{chapter}
\counterwithin{table}{chapter}
\input{files/AppendixA}
\input{files/AppendixB}
```
With an article, you would change this to be...
```
\appendix
\counterwithin{figure}{section}
\counterwithin{table}{section}
\input{files/AppendixA}
\input{files/AppendixB}
```
I have added this to the template file and am going to see if I can just redefine the `\appendix` command to make it invisible to the user.

**Comment by AndyClifton** [comment]
Redefined `\appendix` to implement this automatically. Tested on the `report` and `article` types, probably not functional in memoir.

**Comment by lkilcher** [comment]
Nice!
