### ISSUE TITLE
Font Problems with MikTex

### ISSUE THREAD

**Issue by elainethale** [NREL/latex_editing#4]
First of all, thanks for putting this together! I had worked on something similar but didn't quite push all the way through to making it official.

I am on Windows using MikTeX and Texmaker. I placed the pertinent files in a local tree, updated everything and installed the packages it asked for, but when I try to PDFLaTeX

```latex
\newif\iflatextortf

\iflatextortf
	% tell latex2tortf if this is an article or report
	\documentclass[12pt,letterpaper]{article}
	\input{NRELLatex2rtf.tex}
\else
	\documentclass[report,tagged]{nrel}
\fi

\title{XXXX}
\author{YYYY}

\begin{document}

\maketitle
\frontmatter
\tableofcontents
\clearpage
\listoffigures
\listoftables
\mainmatter

\section{ZZZZ}

\end{document}
```

I get an error:

```
! Font \csname\endcsname=dummy-space at 1.00375pt not loadable: Metric (TFM) fi
le not found.
```

With a little more context:

```
LaTeX Font Info: Font shape `OT1/ptm/bx/n' in size <12> not available
(Font) Font shape `OT1/ptm/b/n' tried instead on input line 7.
LaTeX Font Info: Font shape `OT1/ptm/bx/n' in size <9> not available
(Font) Font shape `OT1/ptm/b/n' tried instead on input line 7.
LaTeX Font Info: Font shape `OT1/ptm/bx/n' in size <7> not available
(Font) Font shape `OT1/ptm/b/n' tried instead on input line 7.
Underfull \hbox (badness 10000) in paragraph at lines 7--7
[][]
[]
Underfull \hbox (badness 10000) in paragraph at lines 7--7
[]\T1/ptm/m/n/12 Wednesday 25$[]$ February, 2015
[]
[1{C:/Users/ehale/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}
! Font \csname\endcsname=dummy-space at 1.00375pt not loadable: Metric (TFM) fi
le not found.
\@EveryShipout@Output ...@Org@Shipout \box \@cclv
l.7 \begin{document}
I wasn't able to read the size data for this font,
so I will ignore the font specification.
[Wizards can fix TFM files using TFtoPL/PLtoTF.]
You might try inserting a different font spec;
e.g., type `I\font<same font id>=<substitute font name>'.
! Font \csname\endcsname=dummy-space at 1.00375pt not loadable: Metric (TFM) fi
le not found.
\@EveryShipout@Output ...@Org@Shipout \box \@cclv
l.7 \begin{document}
```

My guess is that maybe there is a difference between the TexLive and MikTeX fonts ... I will look around some more to see if there is an obvious way to fix this.

**Comment by AndyClifton** [comment]
Hi @elainethale! That's going to be a hard one for me to replicate. I'm using TeX Live 2014. This is from my console window when I'm compiling:

````
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex)
 \write18 enabled.
````

Thinking about it, I do have a system preference set somewhere that would let me switch to MikTeX, but I'm not sure that I have a current MikTex installation. I'll look into this.

**Comment by AndyClifton** [comment]
Oh, and be careful that this isn't really an "official" version yet. We're very much at the beta stage, and you need to be working with your communications rep to make sure that they support you producing documents in 'tex.

**Comment by AndyClifton** [comment]
@elainethale I think we've fixed this. Could you try downloading the new version, compiling _intro_to_NREL_latex.tex_ and see what happens? Thanks!

**Comment by elainethale** [comment]
Thanks for working on this @AndyClifton! I am time-crunched today, but will plan to try out your fix next week.

**Comment by elainethale** [comment]
I am still getting the same errors.

**Comment by elainethale** [comment]
The main problem I had was that I needed to be using XeLaTeX instead of PDFLaTeX. After that, I had to comment out lines 19 and 20,

```
\pdfinterwordspaceon
\pdfminorversion=8
```

in nrel.cls. I think now I am good to go.

**Comment by AndyClifton** [comment]
Glad that's sorted. 

The two commands you commented out suggest you are using an older version of 'tex, maybe? \pdfinterwordspace only exists in tex from 2014 onward.

**Comment by elainethale** [comment]
That seems reasonably likely. I'll upgrade and give that a go. 

Also, just to let you know, I may end up putting in a new issue regarding the fonts. At least for me, the PDFs I am now making are not all that readable. I am not sure if it is the font selection or the font size ...
