### ISSUE TITLE
Fonts are hard to read when compiling with MikTeX on Windows

### ISSUE THREAD

**Issue by elainethale** [NREL/latex_editing#9]
I will send you the pdf I generated, to see if you agree. I am using MiKTeX XeLaTeX on Windows. I upgraded everything as best as I could, but still have to comment out

```
\pdfinterwordspaceon
\pdfminorversion=8
```

**Comment by AndyClifton** [comment]
Can you add the .pdf to the "issues" directory?

**Comment by AndyClifton** [comment]
Fonts are controlled by the nrel.cls file. You'll find the font family is set around line 104:
    % MATHPTMX Times for roman text and math (family ptm)
    \RequirePackage{mathptmx}

NREL requires us to use Times for roman text and math. This seemed the easier option, but if you have ideas for other families to use and how to set them, feel free to make suggestions!

**Comment by elainethale** [comment]
I need permissions to be able to push.

**Comment by elainethale** [comment]
Doing a quick search, I found http://tex.stackexchange.com/a/67769/15802. This specification looks different from what is currently in nrel.cls, but might it be helpful?

**Comment by AndyClifton** [comment]
Debating closing this as this issue does not arise with the NREL-hosted web server (details to follow via direct mail).

**Comment by AndyClifton** [comment]
@elainethale - is this still an issue that we should be looking into?

**Comment by elainethale** [comment]
Not sure at this point. It sounds like there is a server-based workflow I should try? (Readme says details to be provided at a later date ...)

**Comment by elainethale** [comment]
Fonts look okay on my laptop now, and ShareLaTeX is up and running ...
